using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GenerativeLogic.Series
{
    /// <summary>
    /// Represents a type of series.
    /// </summary>
    public enum KnownSeriesType
    {
        /// <summary>
        /// A series that is a stand-in for another series
        /// </summary>
        Stub,
        /// <summary>
        /// A that is generated by an arbitrary process.
        /// </summary>
        Dynamic,
        /// <summary>
        /// Increases the value of the input by one with respet to the numeric context.
        /// </summary>
        Incrementor,
        /// <summary>
        /// Creates the sum of two series in the numeric context
        /// </summary>
        Adder,
        /// <summary>
        /// Provides the value of one of two inputs at each index based on the value of a third input.
        /// </summary>
        Choice,
        /// <summary>
        /// Provides the value of the majority of three values.
        /// </summary>
        Majority,
        /// <summary>
        /// Shifts the input a set number of bits.
        /// </summary>
        Shift,
        /// <summary>
        /// Determines whether one series is numerically greater than another series.
        /// </summary>
        GreaterThan,
        /// <summary>
        /// Determines whether one series is numerically less than another series.
        /// </summary>
        LessThan,
        /// <summary>
        /// Determines whether one series is numerically equal to another series.
        /// </summary>
        Equal,
        /// <summary>
        /// Determines whether one series is numerically not equal to another series.
        /// </summary>
        NotEqual,
        /// <summary>
        /// Determines whether one series is numerically greater than or equal to another series.
        /// </summary>
        GreaterThanOrEqual,
        /// <summary>
        /// Determines whether one series is numerically less than or equal to another series.
        /// </summary>
        LessThanOrEqual
    }
}
